In [2]:
import numpy as np
a=np.array([-1,1]) 

b=np.array([1,1]) 

np.dot(a,b) 

0

In [9]:
X=np.array([[1,0],[0,1]]) 

Y=np.array([[0,1],[1,0]]) 

Z=X+Y 
Z

array([[1, 1],
       [1, 1]])

In [8]:
X=np.array([[1,0,1],[2,2,2]]) 

out=X[0:2,2]
out

array([1, 2])

In [7]:
X=np.array([[1,0],[0,1]])

Y=np.array([[2,2],[2,2]]) 

Z=np.dot(X,Y) 
Z

array([[2, 2],
       [2, 2]])

In [15]:
with open("Example1.txt","r") as file1: 

     FileContent=file1.read() 


print(FileContent) 

This is line 1
This is line 2
This is line 3


In [13]:
with open("Example.txt","w") as writefile: 

    writefile.write("This is line A\n") 

    writefile.write("This is line B\n")

In [14]:
with open('Example2.txt','r') as readfile: 

    with open('Example3.txt','w') as writefile: 

        for line in readfile: 

            writefile.write(line) 

FileNotFoundError: [Errno 2] No such file or directory: 'Example2.txt'

In [16]:
a=np.array([-1,1]) 

b=np.array([1,1]) 

np.dot(a,b) 

0